import 'package:flutter/material.dart';

class CharacterData {
  const CharacterData({
    required this.id,
    required this.name,
    required this.description,
    required this.tags,
    required this.modelPath,
    required this.animationName,
    required this.group,
    required this.primaryColor,
    required this.emoji,
  });

  final String id;
  final String name;
  final String description;
  final List<String> tags;
  final String modelPath;
  final String animationName;
  final String group;
  final Color primaryColor;
  final String emoji;
}

class CharacterSelection {
  CharacterSelection._();

  static CharacterData? selected;
}

const List<CharacterData> characterData = [
  CharacterData(
    id: 'space-astronaut-rae',
    name: 'Phi Hành Gia Gấu Trúc',
    description: 'Rae dẫn đầu chuyến thám hiểm rìa Ngân Hà',
    tags: ['Phi hành gia', 'Khám phá vũ trụ'],
    modelPath: 'assets/3d/Space_Astronaut_RaeTheRedPanda.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFD9D0F5),
    emoji: '👨‍🚀',
  ),
  CharacterData(
    id: 'space-astronaut-finn',
    name: 'Ếch Vũ Trụ Finn',
    description: 'Phi hành gia ếch nhảy xa giữa các tiểu hành tinh',
    tags: ['Trạm không gian', 'Nhà du hành'],
    modelPath: 'assets/3d/Space_Astronaut_FinnTheFrog.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFC9E8D4),
    emoji: '🚀',
  ),
  CharacterData(
    id: 'space-astronaut-fernando',
    name: 'Hồng Hạc Du Hành',
    description: 'Fernando lướt qua tinh vân trên đôi cánh hồng',
    tags: ['Phi hành gia', 'Tinh vân xa xôi'],
    modelPath: 'assets/3d/Space_Astronaut_FernandoTheFlamingo.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFF3D1E1),
    emoji: '🌌',
  ),
  CharacterData(
    id: 'space-astronaut-barbara',
    name: 'Ong Phi Hành',
    description: 'Barbara chăm chỉ khám phá những thế giới mới',
    tags: ['Galaxy', 'Phi hành gia ong'],
    modelPath: 'assets/3d/Space_Astronaut_BarbaraTheBee.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFF7E5B8),
    emoji: '🛸',
  ),
  CharacterData(
    id: 'space-mech-rae',
    name: 'Space Mech Gấu Trúc',
    description: 'Bộ giáp cơ khí tối tân của thuyền trưởng Rae',
    tags: ['Robot chiến đấu', 'Trạm không gian'],
    modelPath: 'assets/3d/Space_Mech_RaeTheRedPanda.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFC9D9F4),
    emoji: '🤖',
  ),
  CharacterData(
    id: 'space-mech-finn',
    name: 'Space Mech Ếch Xanh',
    description: 'Cỗ máy nhảy liên hành tinh của Finn',
    tags: ['Mech phi hành', 'Tuần tra quỹ đạo'],
    modelPath: 'assets/3d/Space_Mech_FinnTheFrog.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFD5E9C8),
    emoji: '🪐',
  ),
  CharacterData(
    id: 'space-mech-fernando',
    name: 'Mech Hồng Hạc',
    description: 'Robot bay thanh thoát bảo vệ đội thám hiểm',
    tags: ['Giáp cơ khí', 'Bay xuyên thiên hà'],
    modelPath: 'assets/3d/Space_Mech_FernandoTheFlamingo.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFF1D5E9),
    emoji: '🚀',
  ),
  CharacterData(
    id: 'space-mech-barbara',
    name: 'Robot Chiến Tạm Space Mech',
    description: 'Mech ong bọc thép sẵn sàng bảo vệ phi hành đoàn',
    tags: ['Robot chiến đấu', 'Bảo vệ phi hành đoàn'],
    modelPath: 'assets/3d/Space_Mech_BarbaraTheBee.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFECE0B9),
    emoji: '🤖',
  ),
  CharacterData(
    id: 'space-enemy-extrasmall',
    name: 'UFO Tí Hon',
    description: 'Sinh vật bay bé xíu lén lút quanh trạm vũ trụ',
    tags: ['Sinh vật ngoài hành tinh', 'Bay quanh quỹ đạo'],
    modelPath: 'assets/3d/Space_Enemy_ExtraSmall.glb',
    animationName: 'Flying_Idle',
    group: 'blob',
    primaryColor: Color(0xFFD4E9F3),
    emoji: '🛸',
  ),
  CharacterData(
    id: 'space-enemy-small',
    name: 'Vệ Binh Sao Băng',
    description: 'Kẻ canh gác nhỏ nhanh nhẹn của vành đai thiên thạch',
    tags: ['Tuần tra thiên hà', 'Tốc độ ánh sáng'],
    modelPath: 'assets/3d/Space_Enemy_Small.glb',
    animationName: 'Flying_Idle',
    group: 'blob',
    primaryColor: Color(0xFFE0D8F2),
    emoji: '🌠',
  ),
  CharacterData(
    id: 'space-enemy-flying',
    name: 'Quái Bay Tinh Vân',
    description: 'Sinh vật bí ẩn lượn giữa những đám mây sao',
    tags: ['Quái vật vũ trụ', 'Ẩn mình trong tinh vân'],
    modelPath: 'assets/3d/Space_Enemy_Flying.glb',
    animationName: 'Flying_Idle',
    group: 'blob',
    primaryColor: Color(0xFFC6E5E9),
    emoji: '🌌',
  ),
  CharacterData(
    id: 'space-enemy-large',
    name: 'Khổng Lồ Hố Đen',
    description: 'Vệ thần khổng lồ canh giữ cổng không gian',
    tags: ['Boss thiên hà', 'Sức mạnh hố đen'],
    modelPath: 'assets/3d/Space_Enemy_Large.glb',
    animationName: 'Idle',
    group: 'blob',
    primaryColor: Color(0xFFD5D2E8),
    emoji: '🌑',
  ),
  CharacterData(
    id: 'pet-cube-1',
    name: 'Hải Ly Thợ Mộc Cube',
    description: 'Bé hải ly chăm chỉ xây chiếc tổ ấm nhất khu rừng',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-beaver.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFD8B89A),
    emoji: '🦫',
  ),
  CharacterData(
    id: 'pet-cube-2',
    name: 'Ong Mật Mũm Mĩm',
    description: 'Cô ong tí hon mang mật ngọt đến mọi cuộc vui',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-bee.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFE59A),
    emoji: '🐝',
  ),
  CharacterData(
    id: 'pet-cube-3',
    name: 'Thỏ Bông Cube',
    description: 'Thỏ con tai dài thích nhảy tung tăng trên mây',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-bunny.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFD6E7),
    emoji: '🐰',
  ),
  CharacterData(
    id: 'pet-cube-4',
    name: 'Mèo Ú Cube',
    description: 'Hoàng thượng béo tròn luôn sẵn sàng nhận một cái ôm',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-cat.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFD3B6),
    emoji: '🐱',
  ),
  CharacterData(
    id: 'pet-cube-5',
    name: 'Sâu Kẹo Cầu Vồng',
    description: 'Bạn sâu nhiều màu bò chầm chậm tìm lá non',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-caterpillar.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFD6F0B8),
    emoji: '🐛',
  ),
  CharacterData(
    id: 'pet-cube-6',
    name: 'Gà Con Bông Gòn',
    description: 'Chíp chíp! Bé gà vàng mê khám phá khu vườn',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-chick.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFF0A8),
    emoji: '🐥',
  ),
  CharacterData(
    id: 'pet-cube-7',
    name: 'Bò Sữa Đốm Nâu',
    description: 'Cô bò hiền lành tặng bạn ly sữa ngon mỗi sáng',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-cow.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFE9DCCB),
    emoji: '🐮',
  ),
  CharacterData(
    id: 'pet-cube-8',
    name: 'Cua Đỏ Kẹp Kẹo',
    description: 'Chú cua nhỏ lắc lư đi ngang bãi biển đầy nắng',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-crab.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFB9AE),
    emoji: '🦀',
  ),
  CharacterData(
    id: 'pet-cube-9',
    name: 'Nai Tơ Đốm Sao',
    description: 'Bé nai nhút nhát thích dạo chơi dưới tán cây',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-deer.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFEBC9A4),
    emoji: '🦌',
  ),
  CharacterData(
    id: 'pet-cube-10',
    name: 'Cún Con Vẫy Đuôi',
    description: 'Người bạn bốn chân trung thành mê chạy theo bóng',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-dog.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFC9DDF4),
    emoji: '🐶',
  ),
  CharacterData(
    id: 'pet-cube-11',
    name: 'Voi Con Tai To',
    description: 'Bé voi phun vòi sen mát rượi cho bạn bè',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-elephant.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFC9E8E8),
    emoji: '🐘',
  ),
  CharacterData(
    id: 'pet-cube-12',
    name: 'Cá Nhỏ Bong Bóng',
    description: 'Chú cá lấp lánh tung tăng trong làn nước xanh',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-fish.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFBFE8F2),
    emoji: '🐟',
  ),
  CharacterData(
    id: 'pet-cube-13',
    name: 'Cáo Cam Tinh Nghịch',
    description: 'Cáo con lanh lợi thích chơi trốn tìm trong rừng',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-fox.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFC89D),
    emoji: '🦊',
  ),
  CharacterData(
    id: 'pet-cube-14',
    name: 'Hươu Cao Cổ Kẹo Bông',
    description: 'Bạn hươu cổ cao ngắm mây và nhấm nháp lá non',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-giraffe.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFDEA1),
    emoji: '🦒',
  ),
  CharacterData(
    id: 'pet-cube-15',
    name: 'Heo Rừng Cuộn Tròn',
    description: 'Bạn heo rừng nhỏ xíu mê lăn mình trên cỏ mềm',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-hog.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFE7C9B6),
    emoji: '🐗',
  ),
  CharacterData(
    id: 'pet-cube-16',
    name: 'Gấu Koala Ôm Cây',
    description: 'Koala bé bỏng ôm cành cây và nhẩn nha ăn lá',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-koala.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFD6D6E8),
    emoji: '🐨',
  ),
  CharacterData(
    id: 'pet-cube-17',
    name: 'Sư Tử Bờm Mềm',
    description: 'Chúa sơn lâm nhí có tiếng gầm bé như tiếng mèo',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-lion.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFD18B),
    emoji: '🦁',
  ),
  CharacterData(
    id: 'pet-cube-18',
    name: 'Khỉ Con Chuối Vàng',
    description: 'Bé khỉ nhanh nhẹn chuyền cành tìm chuối chín',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-monkey.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFDCC9B7),
    emoji: '🐵',
  ),
  CharacterData(
    id: 'pet-cube-19',
    name: 'Gấu Trúc Tròn Xoe',
    description: 'Panda ham ăn chỉ muốn ôm tre và ngủ một giấc ngon',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-panda.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFD4E5D4),
    emoji: '🐼',
  ),
  CharacterData(
    id: 'pet-cube-20',
    name: 'Vẹt Xanh Biết Hót',
    description: 'Chú vẹt sặc sỡ líu lo những giai điệu vui tai',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-parrot.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFC8EBD5),
    emoji: '🦜',
  ),
  CharacterData(
    id: 'pet-cube-21',
    name: 'Cánh Cụt Khăn Len',
    description: 'Bé cánh cụt lon ton trượt băng trên tuyết trắng',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-penguin.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFC9DDF2),
    emoji: '🐧',
  ),
  CharacterData(
    id: 'pet-cube-22',
    name: 'Heo Hồng Cube',
    description: 'Heo con hồng hào thích lội bì bõm trong vũng bùn',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-pig.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFC5D5),
    emoji: '🐷',
  ),
  CharacterData(
    id: 'pet-cube-23',
    name: 'Gấu Bắc Cực Bông Tuyết',
    description: 'Gấu trắng đáng yêu thích ôm cá bên hồ băng xanh',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-polar.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFD7EEFA),
    emoji: '🐻‍❄️',
  ),
  CharacterData(
    id: 'pet-cube-24',
    name: 'Hổ Con Vằn Mật',
    description: 'Bé hổ dũng cảm rón rén khám phá khu rừng xanh',
    tags: ['Pico Pet', 'Thú cưng Cube', 'Đáng yêu'],
    modelPath: 'assets/3d/animal-tiger.glb',
    animationName: 'idle',
    group: 'blob',
    primaryColor: Color(0xFFFFD6A8),
    emoji: '🐯',
  ),
];
